[book]
title = "생각을 코드로"
description = "AI와 함께하는 컴퓨팅 사고 - 일반인편"
authors = ["dimohy"]
language = "ko"
src = "생각을 코드로"

[build]
build-dir = "docs"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/dimohy/CodeWithoutCode"
edit-url-template = "https://github.com/dimohy/CodeWithoutCode/edit/main/{path}"
site-url = "/CodeWithoutCode/"
cname = ""

[output.html.fold]
enable = true
level = 0

[output.html.playground]
editable = false
copyable = true
copy-js = true

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3
